{
  "name": "chlorella-dataset-generator",
  "version": "1.0.0",
  "description": "Generador avanzado de datasets de Chlorella vulgaris",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js",
    "test": "node -e \"console.log('Test OK')\"",
    "postinstall": "mkdir -p generated_datasets"
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "helmet": "^7.0.0",
    "compression": "^1.7.4",
    "winston": "^3.10.0",
    "node-cron": "^3.0.2",
    "multer": "^1.4.5-lts.1"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "keywords": [
    "chlorella",
    "dataset",
    "machine-learning",
    "biotechnology",
    "microalgae"
  ],
  "author": "Dataset Generator",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/tu-usuario/chlorella-generator"
  }
}
